apiVersion: v1
kind: Config

# Where to find the API server
clusters:
- cluster:
    server: https://api:6443
    insecure-skip-tls-verify: true # The API server generates a self-signed certificate on startup if no certs are provided
  name: default
# Define what user to authenticate as
users:
- name: superuser
  user:
    token: 086adda9-1a99-428c-985b-89429d5307ce # This is defined in deploy/static-tokens.txt

# Combine clusters and users into contexts
contexts:
- context:
    cluster: default
    user: superuser
  name: superuser
current-context: superuser
