apiVersion: v1
kind: Node
metadata:
  name: foo-node
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - image: nginx:latest
    name: nginx
    envFrom:
    - secretRef:
        name: missioncritical
    - secretRef:
        name: very-secret
  nodeName: foo-node
---
apiVersion: v1
kind: Secret
metadata:
  name: missioncritical
data:
  supersecret: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
data:
  very-secret: "password"
